### ISSUE TITLE
USE ENUM INSTEAD OF STRING

### ISSUE THREAD

**Issue by alexonozor** [kingkpono/odoo-woocommerce-connector#1]
https://github.com/kingkpono/odoo-woocommerce-connector/blob/57a23f0331781a9ccfe32a07e0962290f6d2f346/controllers/main.py#L8

instead of strings 'processing' use enums to keep values

**Comment by kingkpono** [comment]
Ok, will fix. Thanks

**Comment by kingkpono** [comment]
Fixed. changed order status to enums
